export const LOGIN: string = 'LOGIN'
export const USER_AVAILABLE: string = 'USER_AVAILABLE'
export const USER_UNAVAILABLE: string = 'USER_UNAVAILABLE'
export const GET_GITHUB_USERS: string = 'GET_GITHUB_USERS'
export const GET_GITHUB_USERS_REPO: string = 'GET_GITHUB_USERS_REPO'
export const LOADING: string = 'LOADING'
export const AVATAR: string = 'AVATAR'
